name: cut

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        app= echo "mule-mrcg-integ-realtime-sims-sys" >> $GITHUB_ENV
        echo $app

